### ISSUE TITLE
Dissapearing Crops

### ISSUE THREAD

**Issue by Creeper022** [danbrown/braziliandelight#2]
The two tall crops keep despawning, I think when they try to grow. IE Guaraná, Corn, Cassava. I dont know if this is a byproduct of me using the create mod to harvest them, but Im not having these issued with any other crops.

**Comment by danbrown** [comment]
Hello! I saw this issue happening with mods like Harvest with Ease. Do you have it or any similar installed?

**Comment by cosmicapiary** [comment]
I'm having this issue with carioca beans too, with the RightClickHarvest mod installed (playing on fabric 1.20.1)

**Comment by danbrown** [comment]
Hello @cosmicapiary! I'll check the bug when possible, about carioca beans since it is a bush crop consider adding it to a blacklist if RightClickHarvest has any kind blacklist config.

**Comment by cosmicapiary** [comment]
I've been doing some more testing! RightClickHarvest works properly with collard greens, and they work fine manually broken. the "bush" crops (Guarana, Beans, etc) work fine with RightClickHarvesting disabled, and work pretty inadequately with it. cassava works with just breaking it, but with right click harvesting, each block of it can be harvested seperately, thus "duplicating" it. garlic does not work properly whether right click harvesting or not. right clicking deletes it and ungrows it, and breaking it just drops a single garlic, so it cannot be replanted (or cannot be used)

I hope this helps you narrow things down! I love this mod so much, I'm eager to see it patched up ^^

**Comment by danbrown** [comment]
That helps a lot! Thanks! I will work on it over the next weeks

**Comment by danbrown** [comment]
Issue should be solved in recent versions, I'll reopen if someone report it again

**Comment by cosmicapiary** [comment]
I am very sad to report that these issues persist, at least on fabric ^^'. Collard Greens is still the only crop that functions "normally", and even without right clicking to harvest, the garlic, guarana, and beans all drop only one crop when broken, making them impossible to gain any "profit" from. they all still just evaporate when right click harvesting.
based on all of this, it seems like the crops are intended to be dropping a seed alongside their food, but something is stopping that from happening? it might be a primarily loot table issue (though the two-tall crops do still get harvested separately with rightclickharvest, though that is an issue that effects a lot of two-tall crops)

**Comment by danbrown** [comment]
@cosmicapiary I think I finally found the issue for fabric, the fix will be on the next version
